# Generated by Django 2.0.7 on 2018-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0004_musictrack_liveness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrack',
            name='key',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'C'), (1, 'C#'), (2, 'D'), (3, 'D#'), (4, 'E'), (5, 'F'), (6, 'F#'), (7, 'G'), (8, 'G#'), (9, 'A'), (10, 'A#'), (11, 'B')], null=True),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Minor'), (1, 'Major')], null=True),
        ),
    ]
