# Generated by Django 2.0.7 on 2018-09-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0005_auto_20180812_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musictrack',
            old_name='acousticneses',
            new_name='acousticness',
        ),
    ]
